# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moive_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
     pod 'RealmSwift'
  # Pods for Moive_test

  target 'Moive_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Moive_testUITests' do
    # Pods for testing
  end

end
